name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Java kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Gradle cache
      uses: gradle/gradle-build-action@v3

    - name: Gradle build (APK)
      run: ./gradlew assembleDebug

    - name: APK upload
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
